apiVersion: v1
kind: Secret
metadata:
  name: drepset-secret-wout-annot
  namespace: check-kyverno
  annotations:
    kyverno.opso.info/read: allow
  ownerReferences:
  - apiVersion: apps/v1
    kind: ReplicaSet
    name: drepset-wout-annot-b44578476
    uid: bf93c0d9-8034-4235-96e6-8ee6a1bf480c
type: Opaque
data:
  username: dXNlcm5hbWU=  # base64 encoded username
  password: cGFzc3dvcmQ=  # base64 encoded password
