apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: sync-secret
spec:
  background: true
  generateExistingOnPolicyUpdate: true
  validationFailureAction: audit
  rules:
  - name: sync-secret-to-all-namespaces
    match:
      resources:
        kinds:
        - Namespace
    exclude:
      resources:
        namespaces:
        - "kube*"
        - kyverno
    generate:
      kind: Secret
      apiVersion: v1
      synchronize: true
      name: imagepullsecretcred
      namespace: '{{request.object.metadata.name}}'
      clone:
        name: imagepullsecretcred
        namespace: sourcesecret