apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: secret-daemonset
  namespace: check-kyverno
spec:
  selector:
    matchLabels:
      name: secret-daemonset
  template:
    metadata:
      labels:
        name: secret-daemonset
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        env:
          - name: USERNAME
            valueFrom:
              secretKeyRef:
                name: secret-ds-dment-ss
                key: username
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret-ds-dment-ss
                key: password
