apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-envfrom
  namespace: check-kyverno
  labels:
    app: secret-envfrom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-envfrom
  template:
    metadata:
      labels:
        app: secret-envfrom
    spec:
      containers:
      - name: secret-envfrom-container
        image: nginx
        envFrom:
        - secretRef:
            name: secret-envfrom
