apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-deployment-mount
  namespace: check-kyverno
  labels:
    app: secret-deployment-mount
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-deployment-mount
  template:
    metadata:
      labels:
        app: secret-deployment-mount
        team: cloud
    spec:
      containers:
      - name: secret-dment-cont-mount
        image: alpine
        command: ["sh", "-c", "while :; do echo 'Hello from Alpine with mounted secret'; sleep 10; done"]
        volumeMounts:
        - name: secret-volume
          mountPath: "/etc/secret"
      volumes:
      - name: secret-volume
        secret:
          secretName: secret-ds-dment-ss-second
