apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-deployment-containers
  namespace: check-kyverno
  labels:
    app: secret-deployment-containers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-deployment-containers
  template:
    metadata:
      labels:
        app: secret-deployment-containers
        team: cloud
    spec:
      containers:
      - name: secret-dment-cont-first
        image: nginx:1.21.3
        env:
          - name: SECRET_USERNAME
            valueFrom:
              secretKeyRef:
                name: secret-ds-dment-ss
                key: username
          - name: SECRET_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret-ds-dment-ss
                key: password
      - name: secret-dment-cont-second
        image: alpine
        command: ["sh", "-c", "while :; do echo 'Hello from Alpine with mounted secret'; sleep 10; done"]
        volumeMounts:
        - name: secret-volume
          mountPath: "/etc/secret"
      volumes:
      - name: secret-volume
        secret:
          secretName: secret-ds-dment-ss-second
