apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: secret-statefulset
  namespace: check-kyverno
spec:
  serviceName: "example"
  replicas: 2
  selector:
    matchLabels:
      app: secret-statefulset
  template:
    metadata:
      labels:
        app: secret-statefulset
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        volumeMounts:
        - name: secret-volume
          mountPath: "/etc/secret"
      volumes:
      - name: secret-volume
        secret:
          secretName: secret-ds-dment-ss-second
