apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: configmap-deployment-mount
  name: configmap-deployment-mount
  namespace: check-kyverno
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: configmap-deployment-mount
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: configmap-deployment-mount
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: Always
        name: configmap-dment-container
        volumeMounts:
        - name: config-volume
          mountPath: "/etc/config"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      volumes:
      - name: config-volume
        configMap:
          name: configmap-ds-dment-ss-mount
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
