apiVersion: v1
kind: Secret
metadata:
  name: sset-secret-wout-annot
  namespace: check-kyverno
  annotations:
    kyverno.opso.info/read: allow
  ownerReferences:
  - apiVersion: apps/v1
    kind: StatefulSet
    name: sset-wout-annot
    uid: 6643647a-9461-4686-be8c-2418653619aa
type: Opaque
data:
  username: dXNlcm5hbWU=  # base64 encoded username
  password: cGFzc3dvcmQ=  # base64 encoded password
