apiVersion: batch/v1
kind: Job
metadata:
  name: sample-job
  namespace: check-kyverno
spec:
  template:
    spec:
      containers:
      - name: hello
        image: busybox
        command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']
      restartPolicy: OnFailure
