apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: validate-public-dns-eligible
spec:
  validationFailureAction: Enforce
  rules:
  - name: check-vs-publicdns-eligible
    match:
      any: 
        - resources:
            kinds:
            - networking.istio.io/v1beta1/VirtualService
    exclude:
      resources:
        namespaces:
        - istio-*
    preconditions:
      all:
      - key: "{{ request.object.spec.gateways || [] }}"
        operator: AnyIn
        value: ["istio-system/istio-ingressgateway-public"]
    context:
    - name: allowedPublicHosts
      apiCall:
        urlPath: "/api/v1/namespaces/{{request.namespace}}"
        jmesPath: "metadata.annotations.\"opso.info/allowed-public-hosts\" || ' '"
    validate:
      message: "Your VirtualService contains hosts {{ request.object.spec.hosts[] }} not allowed in namespace `{{request.namespace}}` annotations. Remove the invalid hosts from VirtualService config or contact DevOps."
      deny:
        conditions:
        - key: "{{ request.object.spec.hosts[] }}"
          operator: AnyNotIn
          value: "{{ allowedPublicHosts | replace_all(@, ' ', '') | split(@, ',')}}"
