apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restart-deployment-on-secret-change
  annotations:
    policies.kyverno.io/title: Restart Deployment On Secret Change
    policies.kyverno.io/category: other
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Deployment
    kyverno.io/kyverno-version: 1.10.0
    policies.kyverno.io/minversion: 1.10.0
    kyverno.io/kubernetes-version: "1.25.5"
    policies.kyverno.io/description: >-
      If Secrets are mounted in ways which do not naturally allow updates to
      be live refreshed it may be necessary to modify a Deployment. This policy
      watches a Secret and if it changes will write an annotation
      to one or more target Deployments thus triggering a new rollout and thereby
      refreshing the referred Secret. It may be necessary to grant additional privileges
      to the Kyverno ServiceAccount, via one of the existing ClusterRoleBindings or a new
      one, so it can modify Deployments.
spec:
  mutateExistingOnPolicyUpdate: true
  rules:
  - name: update-secret-in-deploy
    match:
      any:
      - resources:
          kinds:
          - Secret
    preconditions:
      all:
      - key: "{{request.operation}}"
        operator: Equals
        value: UPDATE
      - key: "{{request.object.metadata.ownerReferences[0].kind}}"
        operator: Equals
        value: Deployment
      - key: '{{request.object.metadata.annotations."kyverno.opso.info/read"}}'
        operator: Equals
        value: allow
      - key: "{{ equal_fold('{{request.object.data}}', '{{request.oldObject.data}}') }}"
        operator: NotEquals
        value: true
    mutate:
      targets:
        - apiVersion: apps/v1
          kind: Deployment
          name: "{{ request.object.metadata.ownerReferences[0].name }}"
          namespace: "{{ request.object.metadata.namespace }}"
      patchStrategicMerge:
        spec:
          template:
            metadata:
              annotations:
                kyverno.opso.info/secretversion: "{{request.object.metadata.resourceVersion}}"