apiVersion: v1
kind: Service
metadata:
  name: grpc-service
  namespace: check-kyverno
spec:
  selector:
    app: MyApp
  ports:
    - name: grpc
      port: 13001       # 13000-13049
    - name: grpc-salam
      port: 13049       # 13000-13049