apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: restart-daemonset-on-secret-change
  namespace: check-kyverno
  annotations:
    policies.kyverno.io/title: Restart DaemonSet On Secret Change
    policies.kyverno.io/category: other
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: DaemonSet
    kyverno.io/kyverno-version: 1.7.0
    policies.kyverno.io/minversion: 1.7.0
    kyverno.io/kubernetes-version: "1.23"
    policies.kyverno.io/description: >-
      If Secrets are mounted in ways which do not naturally allow updates to
      be live refreshed it may be necessary to modify a DaemonSet. This policy
      watches a Secret and if it changes will write an annotation
      to one or more target DaemonSets thus triggering a new rollout and thereby
      refreshing the referred Secret. It may be necessary to grant additional privileges
      to the Kyverno ServiceAccount, via one of the existing ClusterRoleBindings or a new
      one, so it can modify DaemonSets.
spec:
  mutateExistingOnPolicyUpdate: true
  rules:
  - name: update-secret
    match:
      any:
      - resources:
          kinds:
          - Secret
          names:
          - webapp-secret
    preconditions:
      all:
      - key: "{{request.operation}}"
        operator: Equals
        value: UPDATE
    mutate:
      targets:
        - apiVersion: apps/v1
          kind: DaemonSet
          name: webapp
          namespace: check-kyverno
      patchStrategicMerge:
        spec:
          template:
            metadata:
              annotations:
                daemonset-version: "{{request.object.metadata.resourceVersion}}"
