apiVersion: v1
kind: Secret
metadata:
  name: dment-secret-wout-annot
  namespace: check-kyverno
  annotations:
    kyverno.opso.info/read: allow
  ownerReferences:
  - apiVersion: apps/v1
    kind: Deployment
    name: dment-wout-annot
    uid: a8707466-55d8-48ca-9bad-705494762505
type: Opaque
data:
  username: dXNlcm5hbWU=  # base64 encoded username
  password: cGFzc3dvcmQ=  # base64 encoded password
