apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-forbiddenusers
  # namespace: default
  # namespace: check-kyverno
  namespace: check-kyverno-policies
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cronjob-forbiddenusers
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
