apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-forbiddenusers
  # namespace: default
  # namespace: check-kyverno
  namespace: check-kyverno-policies
spec:
  serviceName: "statefulset-forbiddenusers"
  replicas: 4
  selector:
    matchLabels:
      app: statefulset-forbiddenusers
  template:
    metadata:
      labels:
        app: statefulset-forbiddenusers
        team: cloud
    spec:
      containers:
      - name: statefulset-forbiddenusers
        image: busybox
        command:
          - sleep
          - "3600"
