apiVersion: v1
kind: Namespace
metadata:
  name: test-dev
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: compliant-statefulset
  namespace: test-dev
spec:
  serviceName: "nginx"
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: k8s.gcr.io/nginx-slim:0.8
