apiVersion: v1
kind: Namespace
metadata:
  name: test-dev
  annotations:
    opso.info/max-replicas: "3"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: violating-hpa-no-annotation
  namespace: test-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
