apiVersion: apps/v1
kind: Deployment
metadata:
  # annotations:
  #   kyverno.opso.lan/secret_dorollout: "allow"
  name: secret-dment-without-annot
  namespace: check-kyverno
  labels:
    app: secret-dment-without-annot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-dment-without-annot
  template:
    metadata:
      labels:
        app: secret-dment-without-annot
        team: cloud
    spec:
      containers:
      - name: app-1
        image: nginx:1.21.3
        env:
          - name: SECRET_USERNAME
            valueFrom:
              secretKeyRef:
                name: secret-ds-dment-ss
                key: username
          - name: SECRET_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret-ds-dment-ss
                key: password