apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kyverno.opso.lan/secret_dorollout: "allow"
  name: secret-statefulset
  namespace: check-kyverno
spec:
  serviceName: "example"
  replicas: 2
  selector:
    matchLabels:
      app: secret-statefulset
  template:
    metadata:
      labels:
        app: secret-statefulset
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        env:
          - name: USERNAME
            valueFrom:
              secretKeyRef:
                name: secret-ds-dment-ss
                key: username
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret-ds-dment-ss
                key: password
