apiVersion: batch/v1
kind: CronJob
metadata:
  name: test-cronjob
  namespace: check-kyverno
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          # hostNetwork: true
          hostPID: true
          containers:
          - name: busybox
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
