apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-hostpidnetwork
  namespace: check-kyverno
spec:
  serviceName: "statefulset-hostpidnetwork"
  replicas: 3
  selector:
    matchLabels:
      app: statefulset-hostpidnetwork
  template:
    metadata:
      labels:
        app: statefulset-hostpidnetwork
        team: devops
    spec:
      # hostNetwork: true
      # hostPID: true
      containers:
      - name: busybox
        image: busybox
        command:
          - sleep
          - "3600"
