apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webapp
  name: webapp
  namespace: check-kyverno
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - image: registry.gitlab.com/gitlab-examples/nginx
        name: nginx
        env:
          - name: DOMAIN
            valueFrom:
              secretKeyRef:
                name: webapp-secret
                key: domain
          - name: OWNER
            valueFrom:
              secretKeyRef:
                name: webapp-secret
                key: owner
          - name: USER
            valueFrom:
              secretKeyRef:
                name: webapp-secret
                key: user