apiVersion: v1
kind: Namespace
metadata:
  name: dev-test
  annotations:
    opso.info/max-replicas: "4"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: dev-test
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        team: devops
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
