apiVersion: v1
kind: Namespace
metadata:
  name: test-dev
  annotations:
    opso.info/max-replicas: "3"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: test-dev
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        team: devops
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
